-- Mortar plants, second step (migration 037 was the first): production lots, spout stops, the
-- bagging target, the standard pace of each product and the price of each raw material.
--
--  * A lot is what the operator asked the mixer for in one go: a recipe and a number of batches.
--    It changes when the recipe changes or when the batch counter is reset for a new run. Its
--    number is generated by the platform (date and time it started), and the bags filled from
--    its first batch until the next lot began belong to it -- that is the traceability.
--  * A stop of a spout is recorded as it happens, like the ceramic stops (migration 032): five-
--    minute buckets know how long a spout stood still, never how many times.

ALTER TABLE mix_batches ADD COLUMN IF NOT EXISTS lot_number text;
CREATE INDEX IF NOT EXISTS mix_batches_device_lot ON mix_batches (device_id, lot_number);
ALTER TABLE mix_runtime ADD COLUMN IF NOT EXISTS lot_number text;
ALTER TABLE mix_runtime ADD COLUMN IF NOT EXISTS lot_recipe text;

CREATE TABLE IF NOT EXISTS bagging_stops (
  id bigserial PRIMARY KEY,
  tenant_id uuid NOT NULL,
  device_id uuid NOT NULL,
  spout_id uuid NOT NULL REFERENCES bagging_spouts (id) ON DELETE CASCADE,
  state text NOT NULL CHECK (state IN ('idle','off')),
  started_at timestamptz NOT NULL,
  ended_at timestamptz NOT NULL,
  seconds double precision NOT NULL,
  recipe text
);
CREATE INDEX IF NOT EXISTS bagging_stops_device_time ON bagging_stops (device_id, started_at);
ALTER TABLE bagging_runtime ADD COLUMN IF NOT EXISTS stop_started_at timestamptz;
ALTER TABLE bagging_runtime ADD COLUMN IF NOT EXISTS stop_state text;

-- The bagging target, per shift, in bags or tons; a day's target is the sum of its shifts.
ALTER TABLE mortar_settings ADD COLUMN IF NOT EXISTS target_metric text NOT NULL DEFAULT 'bags'
  CHECK (target_metric IN ('bags','tons'));
ALTER TABLE mortar_settings ADD COLUMN IF NOT EXISTS target_per_shift double precision
  CHECK (target_per_shift IS NULL OR target_per_shift > 0);

-- Bags per hour a spout should reach on this product: with it the board reads performance.
ALTER TABLE mortar_products ADD COLUMN IF NOT EXISTS standard_rate double precision
  CHECK (standard_rate IS NULL OR standard_rate > 0);

-- What a ton of each raw material costs, by the label the mixer settings use.
CREATE TABLE IF NOT EXISTS mortar_material_prices (
  tenant_id uuid NOT NULL,
  label text NOT NULL CHECK (length(btrim(label)) BETWEEN 1 AND 40),
  price_per_ton double precision NOT NULL CHECK (price_per_ton >= 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, label)
);

-- Applied by hand in the Supabase SQL editor: same three corrections as every platform table.
DO $$
DECLARE
  role_name text;
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['bagging_stops','mortar_material_prices'] LOOP
    EXECUTE format('ALTER TABLE public.%I DISABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC', table_name);
    FOREACH role_name IN ARRAY ARRAY['anon','authenticated'] LOOP
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname=role_name) THEN
        EXECUTE format('REVOKE ALL ON TABLE public.%I FROM %I', table_name, role_name);
      END IF;
    END LOOP;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='everlenz_iiot_app') THEN
      EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON TABLE public.%I TO everlenz_iiot_app', table_name);
    END IF;
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='everlenz_iiot_app') THEN
    GRANT USAGE ON SEQUENCE public.bagging_stops_id_seq TO everlenz_iiot_app;
  END IF;
END $$;
